{% set name = "gridit" %}
{% set version = "0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gridit-{{ version }}.tar.gz
  sha256: 3eec9ee5caee4f94551e4e9a6d6b91c4a934e43d5edac5212888ebeceea40700

build:
  entry_points:
    - gridit = gridit.__main__:cli_main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
    - pip
  run:
    - python >={{ python_min }}
    - fiona
    - affine
    - numpy
    - geopandas
    - rasterio >=1.2.2
    - shapely

test:
  imports:
    - gridit
  commands:
    - pip check
    - gridit --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mwtoews/gridit
  summary: Spatial tools to translate raster or vector geometry data to regular grids
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mwtoews
